server.port: 7771
eureka.client.service-url.defaultZone: http://root:1234@register1:8761/eureka/,http://root:1234@register2:8762/eureka/,http://root:1234@register3:8763/eureka/
eureka.client.healthcheck.enabled: true
eureka.instance.instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
eureka.instance.prefer-ip-address: true

test: '{cipher}48366d5f75d5bee90f9e56de0a6ccc02b1989039826b7aea6dc71a97fe62858c'